setono_sylius_callout_admin_callout:
    resource: |
        section: admin
        alias: setono_sylius_callout.callout
        templates: SetonoSyliusCalloutPlugin:Crud
        permission: true
        redirect: update
        grid: setono_sylius_callout_admin_callout
        vars:
            all:
                templates:
                    form: "@SetonoSyliusCalloutPlugin/Callout/_form.html.twig"
    type: sylius.resource
