setono_sylius_callout_admin_callout:
    resource: |
        section: admin
        alias: setono_sylius_callout.callout
        templates: SyliusAdminBundle:Crud
        permission: true
        redirect: update
        grid: setono_sylius_callout_admin_callout
        vars:
            all:
                templates:
                    form: "@SetonoSyliusCalloutPlugin/Admin/Callout/_form.html.twig"
            index:
                icon: 'bullhorn'
    type: sylius.resource
