sylius_grid:
    grids:
        setono_sylius_callout_admin_callout:
            driver:
                options:
                    class: "%setono_sylius_callout.model.callout.class%"
            fields:
                code:
                    type: string
                    label: setono_sylius_callout.ui.code
                name:
                    type: string
                    label: setono_sylius_callout.ui.name
                enabled:
                    type: twig
                    label: setono_sylius_callout.ui.enabled
                    options:
                        template: SyliusUiBundle:Grid/Field:enabled.html.twig
            filters:
                name:
                    type: string
                    label: setono_sylius_callout.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
