sylius_fixtures:
    suites:
        default:
            fixtures:
                
                locale:
                    options:
                        locales:
                            - "uk_UA"

                product:
                    options:
                        custom:
                            product_setono_jeans_on_sale:
                                name: "Setono Jeans on sale"
                                code: "setono_jeans_on_sale"
                                main_taxon: "mens_jeans"
                                taxons: 
                                    - "mens_jeans"
                                channels:
                                    - "FASHION_WEB"

                setono_sylius_callout:
                    options:
                        custom:
                            callout_today_only:
                                name: "Today only"
                                code: "today-only"
                                text: "Today only"
                                translations:
                                    uk_UA:
                                        text: "Пропозиція дня"
                                position: "bottom_right"
                                priority: 2
                                starts_at: "now"
                                ends_at: "1 day"
                                channels:
                                    - "FASHION_WEB"
                                rules:
                                    - type: "has_product"
                                      configuration:
                                          products: 
                                              - "setono_jeans_on_sale"

                            callout_this_week_only:
                                name: "This week only"
                                code: "this-week-only"
                                text: "This week only"
                                translations:
                                    uk_UA:
                                        text: "Пропозиція тижня"
                                position: "bottom_right"
                                priority: 3
                                starts_at: "now"
                                ends_at: "7 days"
                                channels:
                                    - "FASHION_WEB"
                                rules:
                                    - type: "has_taxon"
                                      configuration:
                                          taxons:
                                              - "books"

                            callout_another_one_callout:
                                name: "Another one callout"
                                code: "another_one_callout"
                                text: "Another one callout"
                                translations:
                                    uk_UA:
                                        text: "Ще один бейдж"
                                position: "bottom_right"
                                priority: 1
                                channels:
                                    - "FASHION_WEB"
                                rules:
                                    - type: "has_taxon"
                                      configuration:
                                          taxons:
                                              - "books"

                            callout_new_product:
                                name: "New"
                                code: "new"
                                text: "New"
                                translations:
                                    uk_UA:
                                        text: "Новинка"
                                position: "top_left"
                                channels:
                                    - "FASHION_WEB"
                                rules:
                                    - type: "is_new"
                                      configuration:
                                          # As far as any product created from fixtures
                                          # have createdAt between -1 week and now
                                          # ~50% of loaded products should have badge 'New'
                                          days: 3

                            callout_new_setono_jeans:
                                name: "New Setono jeans"
                                code: "new_setono_jeans"
                                text: "New Setono jeans"
                                position: "top_right"
                                channels:
                                    - "FASHION_WEB"
                                rules:
                                    - type: "has_product"
                                      configuration:
                                          products: 
                                              - "setono_jeans_on_sale"
                                    - type: "is_new"
                                      configuration:
                                          days: 7
